<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'sort' => '0',
    'type' => '0',
  ),
  2 => 
  array (
    'modelid' => '2',
    'name' => '下载模型',
    'description' => '',
    'tablename' => 'download',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_download',
    'list_template' => 'list_download',
    'show_template' => 'show_download',
    'sort' => '0',
    'type' => '0',
  ),
  3 => 
  array (
    'modelid' => '3',
    'name' => '图片模型',
    'description' => '',
    'tablename' => 'picture',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'sort' => '0',
    'type' => '0',
  ),
  12 => 
  array (
    'modelid' => '12',
    'name' => '漫画模型',
    'description' => '漫画模型',
    'tablename' => 'Cartoon',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'sort' => '0',
    'type' => '0',
  ),
  13 => 
  array (
    'modelid' => '13',
    'name' => '漫画内容模型',
    'description' => '漫画内容模型',
    'tablename' => 'CartoonDetail',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'sort' => '0',
    'type' => '0',
  ),
  14 => 
  array (
    'modelid' => '14',
    'name' => '商品',
    'description' => '商品',
    'tablename' => 'gifts',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show_gifts',
    'sort' => '0',
    'type' => '0',
  ),
  18 => 
  array (
    'modelid' => '18',
    'name' => '动漫内容',
    'description' => '',
    'tablename' => 'dongmanDetail',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  17 => 
  array (
    'modelid' => '17',
    'name' => '动漫',
    'description' => '',
    'tablename' => 'dongman',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => 'category_dongman',
    'list_template' => 'list_dongman',
    'show_template' => 'show_dongman',
    'sort' => '0',
    'type' => '0',
  ),
);
?>