<?php
return array (
  1 => 
  array (
    'typeid' => '1',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '少年热血',
    'parentid' => '0',
    'typedir' => '少年热血',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '少年热血',
  ),
  2 => 
  array (
    'typeid' => '2',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '武侠格斗',
    'parentid' => '0',
    'typedir' => '武侠格斗',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '武侠格斗',
  ),
  3 => 
  array (
    'typeid' => '3',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '少女爱情',
    'parentid' => '0',
    'typedir' => '少女爱情',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '少女爱情',
  ),
  4 => 
  array (
    'typeid' => '4',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '科幻魔幻',
    'parentid' => '0',
    'typedir' => '科幻魔幻',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '科幻魔幻',
  ),
  5 => 
  array (
    'typeid' => '5',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '竞技体育',
    'parentid' => '0',
    'typedir' => '竞技体育',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '竞技体育',
  ),
  6 => 
  array (
    'typeid' => '6',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '搞笑喜剧',
    'parentid' => '0',
    'typedir' => '搞笑喜剧',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '搞笑喜剧',
  ),
  7 => 
  array (
    'typeid' => '7',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '侦探推理',
    'parentid' => '0',
    'typedir' => '侦探推理',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '侦探推理',
  ),
  8 => 
  array (
    'typeid' => '8',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '恐怖灵异',
    'parentid' => '0',
    'typedir' => '恐怖灵异',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '恐怖灵异',
  ),
  9 => 
  array (
    'typeid' => '9',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '耽美BL',
    'parentid' => '0',
    'typedir' => '耽美BL',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '耽美BL',
  ),
  10 => 
  array (
    'typeid' => '10',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => '其他类型',
    'parentid' => '0',
    'typedir' => '其他类型',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '其他类型',
  ),
  11 => 
  array (
    'typeid' => '11',
    'module' => 'content',
    'alias' => '',
    'modelid' => '0',
    'name' => 'H漫画',
    'parentid' => '0',
    'typedir' => 'H漫画',
    'url' => '',
    'template' => '',
    'listorder' => '99',
    'description' => 'H漫画',
  ),
);
?>