<?php return array (
  'name' => '漫画城',
  'author' => 'OLCMS TEAM',
  'dirname' => 'default',
  'homepage' => 'http://www.abc.cn/',
  'version' => '1.0',
  'disable' => 0,
  'file_explan' => 
  array (
    'templates|default|content' => 
    array (
      'category.html' => '文章频道页',
      'category_download.html' => '下载频道页',
      'category_online_comic.html' => '在线漫画',
      'category_picture.html' => '图片频道页',
      'download.html' => '下载连接页',
      'footer.html' => '底部',
      'header.html' => '顶部',
      'header_min.html' => '迷你顶',
      'header_page.html' => '',
      'index.html' => '网站首页',
      'list.html' => '列表页',
      'list_download.html' => '下载列表页',
      'list_picture.html' => '图片列表页',
      'message.html' => '消息提示页',
      'page.html' => '单网页',
      'page_downloads.html' => '单网页-软件下载',
      'rss.html' => 'RSS页',
      'search.html' => '',
      'show.html' => '文章内容页',
      'show_download.html' => '下载内容页',
      'show_picture.html' => '图片内容页',
      'tag.html' => '',
    ),
    'templates|default|' => 
    array (
      'announce' => '广告',
      'comment' => '评论',
      'content' => '内容模型',
      'feedback' => '用户留言',
      'formguide' => '',
      'link' => '友情链接',
      'member' => '会员中心',
      'message' => '短消息',
      'mood' => '新闻心情',
      'pay' => '支付',
      'poster' => '广告',
      'search' => '搜索',
      'special' => '专题',
      'vote' => '投票',
    ),
    'templates|default|vote' => 
    array (
      'list_new.html' => '',
      'show.html' => '展示页',
      'submit.html' => '',
      'vote_result.html' => '',
      'vote_tp.html' => '单独显示页',
      'vote_tp_2.html' => '新闻页投票模版',
      'vote_tp_3.html' => '首页投票模版',
    ),
    'templates|default|link' => 
    array (
      'index.html' => '首页',
      'list_type.html' => '分类页',
      'register.html' => '申请页',
    ),
    'templates|default|special' => 
    array (
      'api_picture.html' => '组图',
      'comment.html' => '专题首页评论页',
      'header.html' => '专题头部',
      'index.html' => '专题首页',
      'list.html' => '分类页',
      'show.html' => '内容页',
      'special_list.html' => '专题列表',
    ),
    'templates|default|poster' => 
    array (
      'banner.html' => '矩形横幅',
      'couplet.html' => '对联广告',
      'fixure.html' => '固定位置',
      'float.html' => '漂浮移动',
      'imagechange.html' => '图片轮换广告',
      'imagelist.html' => '图片列表广告',
      'test.html' => '',
      'text.html' => '文字广告',
    ),
    'templates|default|announce' => 
    array (
      'show.html' => '内容页',
    ),
    'templates|default|comment' => 
    array (
      'show_list.html' => '内容页评论列表',
      'list.html' => '评论列表',
    ),
    'templates|comic|content' => 
    array (
      'category.html' => '文章模型',
      'category_comic_city.html' => '动漫城',
      'category_comic_jb.html' => '漫画捷报',
      'category_comic_news.html' => '漫画资讯',
      'category_download.html' => '下载模型',
      'category_online_comic.html' => '在线动漫',
      'category_picture.html' => '图片模型',
      'category_ranking_list.html' => '排行榜',
      'download.html' => '',
      'footer.html' => '',
      'header.html' => '',
      'header_min.html' => '',
      'header_page.html' => '',
      'index.html' => '',
      'list.html' => '',
      'list_download.html' => '',
      'list_picture.html' => '',
      'message.html' => '',
      'page.html' => '',
      'page_downloads.html' => '单页-软件下载',
      'rss.html' => '',
      'search.html' => '',
      'show.html' => '',
      'show_download.html' => '',
      'show_picture.html' => '',
      'tag.html' => '',
    ),
  ),
);?>